### PR TITLE
Offline validator junit check consistensy

### PR DESCRIPTION
**Pull request by niko-rodrigue**
addition of javadoc and fix of the call to checkConsistency

### CODE REVIEW

**Comment by niko-rodrigue** [comment]
@Onur101010 may be you have changed the indentation of your file since last time. It seems to be using too much spaces (like 4 instead of 2) and it does create conflicts so we cannot automatically merge your changes. Can you have a look at it ? Check with @DEVetter if needed as I think he had a similar issue.
Once you have done some changes on your branch, you can check again here to see if the branch can be merged without conflict. When you look at the changes on your files, you should not see the entire file, that's not good. You should only see the small part that you changed.

**Comment by Onur101010** [comment]
@niko-rodrigue Yes I actually changed something. I imported the code templates in the eclipse preferences. I will have a look at it this evening. Thank you.

**Comment by Onur101010** [comment]
@niko-rodrigue I reset the changes on the formatter settings of eclipse back to standard and repushed the branch but to me (before and after changing settings) it only shows one conflict and it's only the part I actually changed in the code. So I don't really know why it is even detected as a conflict... 

But maybe it should be this way because I'm actually changing code which was already in master (this branch was already merged into master, I just added the javadoc afterwards)?

**Comment by niko-rodrigue** [comment]
If you look at https://github.com/sbmlteam/jsbml/pull/190/files#diff-d1c245ec9aa8de994870d0329ac50d2e it show only one line in green ? Anyway, looking at the file, the indentation is still wrong with too much spaces for each indent.
If you look at https://github.com/sbmlteam/jsbml/commit/e02e3d97e7eff4c3c582e74a78a0c51625bfa67c#diff-d1c245ec9aa8de994870d0329ac50d2e lines 79-230 there the indentation look good with 2 spaces for each indentation.

**Comment by Onur101010** [comment]
No it does'nt but it shows the last 10 commits, and some of them were already in master. If I look at https://github.com/sbmlteam/jsbml/pull/190/commits/aa77576b89b789426844840917f99fa5140bd648 it shows only the addition of javadoc which should be right as I understand. 

I will look further into the identation problem though.

**Comment by Onur101010** [comment]
I reindented the whole code again under https://github.com/sbmlteam/jsbml/pull/190/commits/266aba6c8479fa03b2288aebb6ea7368dbae6f36 . 
This will cause probably again a merge conflict because it changed indentation for every line almost but can you please look at the code again if it looks good now?

**Comment by niko-rodrigue** [comment]
All merged now. You have a good example of why indentation/re-formatting large chunck of code can be a pain when working on different branches and different people. Instead of a one click merge you have to go through painful merge by hand.

**Pull request merged**
